name: process_manager
description: "进程管理器 - 一个简单的进程管理工具"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path: ^1.9.0
  process_run: ^1.2.4
  window_manager: ^0.4.3
  charcode: ^1.3.1
  gbk_codec: ^0.4.0
  flutter_launcher_icons: "^0.13.1"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
# 在 pubspec.yaml 的底部

flutter_launcher_icons:
  # 针对所有平台 (android, ios, macos, windows, linux) 都设为 true
  android: true
  ios: true
  image_path: "assets/icons/icon.png" # 指向你的图标文件
  min_sdk_android: 21 # 可选
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 256 # windows 的 .ico 文件的主尺寸
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

